services:
  backend1:
    build: ./backend
    restart: "no"
    environment:
      - BACKEND_ID=backend-1
    networks:
      - app-network

  backend2:
    build: ./backend
    restart: "no"
    environment:
      - BACKEND_ID=backend-2
    networks:
      - app-network

  backend3:
    build: ./backend
    restart: "no"
    environment:
      - BACKEND_ID=backend-3
    networks:
      - app-network

  mongo1:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata1:/data/db
    environment:
      - MONGO_ID=mongo-1
    networks:
      - app-network

  mongo2:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    volumes:
      - dbdata2:/data/db
    environment:
      - MONGO_ID=mongo-2
    networks:
      - app-network

  mongo3:
    image: mongo:6-jammy
    ports:
      - "27019:27017"
    volumes:
      - dbdata3:/data/db
    environment:
      - MONGO_ID=mongo-3
    networks:
      - app-network

  mongo-gestor:
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - dbdata3:/data/db
    environment:
      - MONGO_ID=mongo-3
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata1:
  dbdata2:
  dbdata3: