GET http://localhost:3000/prodotti

#################################

GET http://localhost:3000/prodotti/2

#################################

GET http://localhost:3000/stresstest

###############################

GET http://localhost:80/ping


############################

POST http://localhost:80/job-for-all
Content-Type: application/json

{
    "name": "esempio di job"
}

#####################

POST http://localhost:80/pdf
Content-Type: application/json

{
    "url": "https://itsaltoadriatico.it"
}